### ISSUE TITLE
Intercepting `Content-Disposition: attachment` Responses

### ISSUE THREAD

**Issue by tclancy** [zoehneto/chrome-rtf-viewer#1]
How difficult would it be to update the extension to strip `Content-Disposition: attachment` from RTF responses so viewers have a chance to see the file in the browser? For Chromebook users, if an RTF file is forced as a download, there's no way to get it open in the extension. Per [this StackOverflow answer](http://stackoverflow.com/a/27771671/7376) it looks like the easiest thing is to just rewrite the header at intercept (or maybe remove it entirely in this case?).

**Comment by zoehneto** [comment]
I'I have a look at it later, do you have a url for testing this?

**Comment by zoehneto** [comment]
I'm currently publishing a new version (1.0.2), which has improved content-type handling and should fix multiple issues. With this change content-disposition doesn't cause problems on dropbox, so please test whether it also fixes your issue.

**Comment by tclancy** [comment]
Wow, you beat me to it-- I was going to take the task on since I opened the issue (all of my test urls are at a site I can't provide access to so I'd need to check it). I will try it out once the updated version is published. Thanks again!

**Comment by zoehneto** [comment]
No problem :) It's finally published now, took a little longer than usual.

**Comment by tclancy** [comment]
No, the changes here didn't seem to make a difference. The `Content-Disposition: attachment` header will need to be removed entirely (or adjusted). Want me to handle this internally or do you want to take the first crack?

**Comment by zoehneto** [comment]
Might be best if you do it, since I can't reproduce the issue.

**Comment by tclancy** [comment]
Closing this: it's an issue with the site and not the extension: they are serving the files as `application/msword` and there's no extension on the file at all.

**Comment by zoehneto** [comment]
If you can't fix the site which delivers these files, there's still the option of adding an action to the right click menu that opens a link in the extension, no matter what the file extension or content type is.

**Comment by tclancy** [comment]
If only they'd make it that easy: the links actually cause a form post which serves the file out with `Content-Disposition: inline` but I can't seem to intercept those headers.

**Comment by zoehneto** [comment]
While you could probably get those headers with either `onResponseStarted` or `onCompleted`, at that point you can't redirect the response anymore. The only suggestion i have seen is to override the XMLHttpRequest as mentioned in [this Stackoverflow post](http://stackoverflow.com/a/18316107), but that might also not work because of the form submit and CORS. If that works you could load the data and check whether it starts with `{\rtf1` and if it doesn't just force it to be downloaded.
